production:
  phpSettings:
    display_startup_errors: 0
    display_errors: 0
  applicationNamespace: "ArooCMS"

test:
  _inherits: production
  phpSettings:
    display_startup_errors: 1
    display_errors: 1

development:
  _inherits: production
  phpSettings:
    display_startup_errors: 1
    display_errors: 1